---
- name: Install Node global packages
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ nodejs_global }}'

- name: Install Volta Node manager
  command: 'curl https://get.volta.sh | bash'
