---
- name: Install taps
  homebrew_tap:
    name: '{{ item }}'
  with_items: '{{ homebrew_taps }}'

- name: Update Homebrew and upgrade all packages
  homebrew:
    update_homebrew: yes

- name: Install Homebrew packages
  homebrew:
    name: '{{ homebrew_packages }}'

- name: Install Homebrew cask applications
  homebrew_cask:
    name: '{{ item }}'
  with_items: '{{ homebrew_cask_apps }}'

- name: Cleanup Homebrew packages
  command: brew cleanup -s
